### ISSUE TITLE
Printer does not recognize right half of the bed

### ISSUE THREAD

**Issue by cgarcia2097** [torontomulibrary/DMEPrintrbotWhite#2]
When using the Simple White, manual controls fail to move the extruder head past the left half of the bed. The issue is exacerbated by prints failing to recognize right half of the bed and printing the rightmost part of the model in the middle of the print. 

This has happened with multiple prints in the past, please check if printer offsets are set correctly.

**Comment by DongerZonie** [comment]
Fixed by changing the printer volume in the printer profile settings in octoprint
